/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Networking(props) {
    const { nodes, materials } = useGLTF('3D/models/skills/networking.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={materials['Material.001']}
                position={[0, 2.507, 0]}
                scale={[1, 2.203, 3.92]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Text.geometry}
                material={materials['Material.002']}
                position={[1.02, 0.797, 1.897]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.404}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.networking.geometry}
                material={materials.networking}
                position={[1.144, 2.83, 0]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[2.008, 2.008, 2.729]}
            />
        </group>
    )
}

useGLTF.preload('3D/models/skills/networking.glb')
