/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ShreeKrishna(props) {
  const { nodes, materials } = useGLTF('3D/models/shree_krishna.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-29.125, 0, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials['Sparkly Gold']}
          position={[0, -29.125, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('3D/models/shree_krishna.glb')