/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/shree_ram.glb 
Author: krissyadavkr (https://sketchfab.com/krissyadavkr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ram-ji-3d-model-5633dfb93ba5439fa6a8063c4e3afea8
Title: Ram ji 3d model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ShreeRam(props) {
  const { nodes, materials } = useGLTF('3D/models/shree_ram.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.ARROW} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Female_Angled.001']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Female_Angled_Base.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Hair.003']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Hair.003']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Hair.005']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Scalp.001']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Std_Cornea_L.001']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Std_Cornea_R.001']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Std_Eye_L.001']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Std_Eye_Occlusion_L.001']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Std_Eye_Occlusion_R.001']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Std_Eye_R.001']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Std_Eyelash.001']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Std_Nails.001']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Std_Skin_Arm.001']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['Std_Skin_Body.001']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['Std_Skin_Head.001']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Std_Skin_Leg.001']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.beads} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.dhoti} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.dhoti} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.dhoti} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.dhoti} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.rock1} />
      </group>
    </group>
  )
}

useGLTF.preload('3D/models/shree_ram.glb')
