/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/3D/models/shree_krishna.glb 
Author: Ragesh (https://sketchfab.com/Ragesh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/krishna-3d-model-3d-print-54fddd6f00d140119bc50bd141083fe6
Title: Krishna 3D model 3D print
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ShreeKrishna(props) {
  const { nodes, materials } = useGLTF('3D/models/shree_krishna.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow
        receiveShadow geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('3D/models/shree_krishna.glb')
