/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useFBX, useAnimations } from '@react-three/drei'

export function Vishal(props) {

    const { animation } = props;

    // ---------------- useGLTF
    const { nodes, materials } = useGLTF('3D/models/vishal.glb');

    // ---------------- use refs
    const group = useRef();

    // ---------------- animations
    const { animations: IdleToSprint } = useFBX('3D/animations/Idle_To_Sprint.fbx');
    const { animations: Flying } = useFBX('3D/animations/Flying.fbx');
    const { animations: FallingToRoll } = useFBX('3D/animations/Falling_To_Roll.fbx');
    const { animations: JumpOver } = useFBX('3D/animations/Jump_Over.fbx');

    IdleToSprint[0].name = 'IdleToSprint';
    Flying[0].name = 'Flying';
    FallingToRoll[0].name = 'FallingToRoll';
    JumpOver[0].name = 'JumpOver';

    const { actions } = useAnimations([IdleToSprint[0], Flying[0], FallingToRoll[0], JumpOver[0]], group);

    // ---------------- useEffect
    useEffect(() => {
        actions[animation].reset().fadeIn(1).play();
        return () => actions[animation].reset().fadeOut(1);
    }, [animation]);

    return (
        <group {...props} ref={group} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} frustumCulled={false}>
                <primitive object={nodes.Hips} />
                <skinnedMesh
                    frustumCulled={false}
                    name="EyeLeft"
                    geometry={nodes.EyeLeft.geometry}
                    material={materials.Wolf3D_Eye}
                    skeleton={nodes.EyeLeft.skeleton}
                    morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
                    morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="EyeRight"
                    geometry={nodes.EyeRight.geometry}
                    material={materials.Wolf3D_Eye}
                    skeleton={nodes.EyeRight.skeleton}
                    morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
                    morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="Wolf3D_Head"
                    geometry={nodes.Wolf3D_Head.geometry}
                    material={materials.Wolf3D_Skin}
                    skeleton={nodes.Wolf3D_Head.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="Wolf3D_Teeth"
                    geometry={nodes.Wolf3D_Teeth.geometry}
                    material={materials.Wolf3D_Teeth}
                    skeleton={nodes.Wolf3D_Teeth.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    geometry={nodes.Wolf3D_Hair.geometry}
                    material={materials.Wolf3D_Hair}
                    skeleton={nodes.Wolf3D_Hair.skeleton}
                />
                <skinnedMesh
                    frustumCulled={false}
                    geometry={nodes.Wolf3D_Glasses.geometry}
                    material={materials.Wolf3D_Glasses}
                    skeleton={nodes.Wolf3D_Glasses.skeleton}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="Wolf3D_Outfit_Top"
                    geometry={nodes.Wolf3D_Outfit_Top.geometry}
                    material={materials.Wolf3D_Outfit_Top}
                    skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Outfit_Top.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Outfit_Top.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="Wolf3D_Outfit_Bottom"
                    geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
                    material={materials.Wolf3D_Outfit_Bottom}
                    skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Outfit_Bottom.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Outfit_Bottom.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="Wolf3D_Outfit_Footwear"
                    geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
                    material={materials.Wolf3D_Outfit_Footwear}
                    skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Outfit_Footwear.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Outfit_Footwear.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="Wolf3D_Body"
                    geometry={nodes.Wolf3D_Body.geometry}
                    material={materials.Wolf3D_Body}
                    skeleton={nodes.Wolf3D_Body.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Body.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Body.morphTargetInfluences}
                />
            </group>
        </group >
    )
}

useGLTF.preload('3D/models/vishal.glb');
useGLTF.preload('3D/animations/Idle_To_Sprint.fbx');
useGLTF.preload('3D/animations/Flying.fbx');
useGLTF.preload('3D/animations/Falling_To_Roll.fbx');
useGLTF.preload('3D/animations/Jump_Over.fbx');
