/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useFBX, useAnimations } from '@react-three/drei'

export function Vishal(props) {

    const { animation } = props;

    // ---------------- useGLTF
    const { nodes, materials } = useGLTF('3D/models/vishal.glb');

    // ---------------- use refs
    const group = useRef();

    // ---------------- animations
    const { animations: Kneeling } = useFBX('3D/animations/Kneeling.fbx');
    const { animations: FallDown } = useFBX('3D/animations/Fall_Down.fbx');
    const { animations: FallStraight } = useFBX('3D/animations/Fall_Straight.fbx');
    const { animations: LeanStand } = useFBX('3D/animations/Lean_stand.fbx');
    const { animations: LeanThinking } = useFBX('3D/animations/Lean_Thinking.fbx');
    const { animations: SitStraight } = useFBX('3D/animations/Sit_straight.fbx');
    const { animations: SitTired } = useFBX('3D/animations/Sit_tired.fbx');
    const { animations: Laying } = useFBX('3D/animations/Laying.fbx');

    Kneeling[0].name = 'Kneeling';
    FallDown[0].name = 'FallDown';
    FallStraight[0].name = 'FallStraight';
    LeanStand[0].name = 'LeanStand';
    LeanThinking[0].name = 'LeanThinking';
    SitStraight[0].name = 'SitStraight';
    SitTired[0].name = 'SitTired';
    Laying[0].name = 'Laying';

    const { actions } = useAnimations([Kneeling[0], FallStraight[0], FallDown[0], LeanStand[0], LeanThinking[0], SitStraight[0], SitTired[0], Laying[0]], group);

    // ---------------- useEffect
    useEffect(() => {
        group.current.rotation.x = -Math.PI / 2;

        actions[animation].reset().fadeIn(0.5).play();
        return () => actions[animation].reset().fadeOut(0.5);
    }, [animation]);

    return (
        <group {...props} ref={group} dispose={null}>
            <group rotation={[0, 0, -0.4]} frustumCulled={false}>
                <primitive object={nodes.Hips} />
                <skinnedMesh
                    frustumCulled={false}
                    name="EyeLeft"
                    geometry={nodes.EyeLeft.geometry}
                    material={materials.Wolf3D_Eye}
                    skeleton={nodes.EyeLeft.skeleton}
                    morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
                    morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="EyeRight"
                    geometry={nodes.EyeRight.geometry}
                    material={materials.Wolf3D_Eye}
                    skeleton={nodes.EyeRight.skeleton}
                    morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
                    morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="Wolf3D_Head"
                    geometry={nodes.Wolf3D_Head.geometry}
                    material={materials.Wolf3D_Skin}
                    skeleton={nodes.Wolf3D_Head.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="Wolf3D_Teeth"
                    geometry={nodes.Wolf3D_Teeth.geometry}
                    material={materials.Wolf3D_Teeth}
                    skeleton={nodes.Wolf3D_Teeth.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    geometry={nodes.Wolf3D_Hair.geometry}
                    material={materials.Wolf3D_Hair}
                    skeleton={nodes.Wolf3D_Hair.skeleton}
                />
                <skinnedMesh
                    frustumCulled={false}
                    geometry={nodes.Wolf3D_Glasses.geometry}
                    material={materials.Wolf3D_Glasses}
                    skeleton={nodes.Wolf3D_Glasses.skeleton}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="Wolf3D_Outfit_Top"
                    geometry={nodes.Wolf3D_Outfit_Top.geometry}
                    material={materials.Wolf3D_Outfit_Top}
                    skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Outfit_Top.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Outfit_Top.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="Wolf3D_Outfit_Bottom"
                    geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
                    material={materials.Wolf3D_Outfit_Bottom}
                    skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Outfit_Bottom.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Outfit_Bottom.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="Wolf3D_Outfit_Footwear"
                    geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
                    material={materials.Wolf3D_Outfit_Footwear}
                    skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Outfit_Footwear.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Outfit_Footwear.morphTargetInfluences}
                />
                <skinnedMesh
                    frustumCulled={false}
                    name="Wolf3D_Body"
                    geometry={nodes.Wolf3D_Body.geometry}
                    material={materials.Wolf3D_Body}
                    skeleton={nodes.Wolf3D_Body.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Body.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Body.morphTargetInfluences}
                />
            </group>
        </group >
    )
}

useGLTF.preload('3D/models/vishal.glb');

useGLTF.preload('3D/animations/Kneeling.fbx');
useGLTF.preload('3D/animations/Fall_Down.fbx');
useGLTF.preload('3D/animations/Fall_Straight.fbx');
useGLTF.preload('3D/animations/Lean_stand.fbx');
useGLTF.preload('3D/animations/Lean_Thinking.fbx');
useGLTF.preload('3D/animations/Sit_straight.fbx');
useGLTF.preload('3D/animations/Sit_tired.fbx');
useGLTF.preload('3D/animations/Laying.fbx');