/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Background(props) {
    const { nodes, materials } = useGLTF('3D/models/night_sky.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['adelin-preda--tOr_T4qTpQ-unsplash'].geometry}
                material={materials['adelin-preda--tOr_T4qTpQ-unsplash']}
                position={[3, 0, -4]}
                rotation={[-Math.PI / 2, Math.PI / 1, Math.PI / 100]}
                scale={35}
            />
        </group>
    )
}

useGLTF.preload('3D/models/night_sky.glb')